export const fakeOrders = [
  {
    id: "0sqqNhBzKaUUlUHidqG0",
    price: 740,
    quantity: 3,
    status: "на проверке",
    title: "Web Разработка",
    description: "Description for order 1",
  },
  {
    id: "1XhgggCFlgPhUau5M2pf",
    price: 220.0,
    quantity: 2,
    status: "одобрено",
    title: "Электроника и гаджеты",
    description: "Description for order 2",
  },
  {
    id: "D4q4NXnIxXxtpZAPG4BH",
    price: 4200,
    quantity: 1,
    status: "на проверке",
    title: "Робототехника",
    description: "Description for order 3",
  },
  {
    id: "FFc57rWzrnAW1ytpOB6Z",
    price: 1900,
    quantity: 3,
    status: "на проверке",
    title: "Смарт-дом",
    description: "Description for order 4",
  },
  {
    id: "HimZKF9Rb19YTSoVx5O1",
    price: 470,
    quantity: 2,
    status: "одобрено",
    title: "Геймерский набор",
    description: "Description for order 5",
  },
  {
    id: "Osvgv7JIabd8G845KQry",
    price: 350,
    quantity: 1,
    status: "на проверке",
    title: "VR-опыт",
    description: "Description for order 6",
  },
  {
    id: "Zzepkmt8VVXeVCryoOXR",
    price: 120,
    quantity: 5,
    status: "отклонено",
    title: "Образовательные игрушки",
    description: "Description for order 7",
  },
  {
    id: "cobuVKt9ckg7812yquUu",
    price: 800,
    quantity: 2,
    status: "одобрено",
    title: "Стационарный компьютер",
    description: "Description for order 8",
  },
  {
    id: "noCRFuSSZBiouB4EoXVr",
    price: 77,
    quantity: 1,
    status: "на проверке",
    title: "Электронные книги",
    description: "Description for order 9",
  },
  {
    id: "pxszNDUri3PmHiPmkN6V",
    price: 200,
    quantity: 4,
    status: "одобрено",
    title: "Гарнитур для стриминга",
    description: "Description for order 10",
  },
  {
    id: "qFjlVKWnR3BVExaNMzFs",
    price: 999,
    quantity: 2,
    status: "отклонено",
    title: "Солнечные батареи",
    description: "Description for order 11",
  },
  {
    id: "t2Rkvz6v95XFxHZ50auf",
    price: 13000,
    quantity: 3,
    status: "на проверке",
    title: "Спутниковая навигация",
    description: "Description for order 12",
  },
  {
    id: "tCguBYxS5ykXenU2GT3l",
    price: 680,
    quantity: 1,
    status: "одобрено",
    title: "Фото и видео оборудование",
    description: "Description for order 13",
  },
  {
    id: "wVCNF5kw6QWvGqxmGVtw",
    price: 120,
    quantity: 2,
    status: "на проверке",
    title: "Умные очки",
    description: "Description for order 14",
  },
  {
    id: "wXGZ2aMk4ZocNwrrnAQ6",
    price: 60,
    quantity: 3,
    status: "одобрено",
    title: "Робот-пылесос",
    description: "Description for order 15",
  },
  {
    id: "xFd9d3pta46nDl5oYJM8",
    price: 400,
    quantity: 1,
    status: "на проверке",
    title: "Смартфон нового поколения",
    description: "Description for order 16",
  },
  {
    id: "gh111",
    price: 9999,
    quantity: 2,
    status: "отклонено",
    title: "Безопасность в интернете",
    description: "Description for order 17",
  },
  {
    id: "ij212",
    price: 40000,
    quantity: 4,
    status: "одобрено",
    title: "Суперкомпьютер",
    description: "Description for order 18",
  },
  {
    id: "kl313",
    price: 290,
    quantity: 1,
    status: "на проверке",
    title: "Игровая консоль",
    description: "Description for order 19",
  },
  {
    id: "mn4aa2wW14",
    price: 555,
    quantity: 3,
    status: "одобрено",
    title: "Экологичная электроника",
    description: "Description for order 20",
  },
  {
    id: "gh1ceqzqc11",
    price: 13.25,
    quantity: 2,
    status: "отклонено",
    title: "Беспроводные наушники",
    description: "Description for order 21",
  },
  {
    id: "ij2sssxqxw12",
    price: 3400,
    quantity: 4,
    status: "одобрено",
    title: "Искусственный интеллект",
    description: "Description for order 22",
  },
];
