export const fakeOrders = [
  {
    id: "0sqqNhBzKaUUlUHidqG0",
    price: 15.99,
    quantity: 3,
    status: "in process",
    description: "Description for order 1",
  },
  {
    id: "1XhgggCFlgPhUau5M2pf",
    price: 24.5,
    quantity: 2,
    status: "fulfilled",
    description: "Description for order 2",
  },
  {
    id: "D4q4NXnIxXxtpZAPG4BH",
    price: 32.0,
    quantity: 1,
    status: "in process",
    description: "Description for order 3",
  },
  {
    id: "FFc57rWzrnAW1ytpOB6Z",
    price: 15.99,
    quantity: 3,
    status: "in process",
    description: "Description for order 4",
  },
  {
    id: "HimZKF9Rb19YTSoVx5O1",
    price: 24.5,
    quantity: 2,
    status: "fulfilled",
    description: "Description for order 5",
  },
  {
    id: "Osvgv7JIabd8G845KQry",
    price: 32.0,
    quantity: 1,
    status: "in process",
    description: "Description for order 6",
  },
  {
    id: "Zzepkmt8VVXeVCryoOXR",
    price: 10.0,
    quantity: 5,
    status: "rejected",
    description: "Description for order 7",
  },
  {
    id: "cobuVKt9ckg7812yquUu",
    price: 45.75,
    quantity: 2,
    status: "fulfilled",
    description: "Description for order 8",
  },
  {
    id: "noCRFuSSZBiouB4EoXVr",
    price: 18.0,
    quantity: 1,
    status: "in process",
    description: "Description for order 9",
  },
  {
    id: "pxszNDUri3PmHiPmkN6V",
    price: 28.99,
    quantity: 4,
    status: "fulfilled",
    description: "Description for order 10",
  },
  {
    id: "qFjlVKWnR3BVExaNMzFs",
    price: 12.5,
    quantity: 2,
    status: "rejected",
    description: "Description for order 11",
  },
  {
    id: "t2Rkvz6v95XFxHZ50auf",
    price: 36.75,
    quantity: 3,
    status: "in process",
    description: "Description for order 12",
  },
  {
    id: "tCguBYxS5ykXenU2GT3l",
    price: 22.0,
    quantity: 1,
    status: "fulfilled",
    description: "Description for order 13",
  },
  {
    id: "wVCNF5kw6QWvGqxmGVtw",
    price: 8.5,
    quantity: 2,
    status: "in process",
    description: "Description for order 14",
  },
  {
    id: "wXGZ2aMk4ZocNwrrnAQ6",
    price: 19.99,
    quantity: 3,
    status: "fulfilled",
    description: "Description for order 15",
  },
  {
    id: "xFd9d3pta46nDl5oYJM8",
    price: 50.0,
    quantity: 1,
    status: "in process",
    description: "Description for order 16",
  },
  {
    id: "gh111",
    price: 13.25,
    quantity: 2,
    status: "rejected",
    description: "Description for order 17",
  },
  {
    id: "ij212",
    price: 30.5,
    quantity: 4,
    status: "fulfilled",
    description: "Description for order 18",
  },
  {
    id: "kl313",
    price: 14.0,
    quantity: 1,
    status: "in process",
    description: "Description for order 19",
  },
  {
    id: "mn4aa2wW14",
    price: 40.0,
    quantity: 3,
    status: "fulfilled",
    description: "Description for order 20",
  },
  {
    id: "gh1ceqzqc11",
    price: 13.25,
    quantity: 2,
    status: "rejected",
    description: "Description for order 21",
  },
  {
    id: "ij2sssxqxw12",
    price: 30.5,
    quantity: 4,
    status: "fulfilled",
    description: "Description for order 22",
  },
];
