export const fakeOrders = [
  {
    id: "order-1_abc123",
    price: 15.99,
    quantity: 3,
    status: "in process",
    description: "Description for order 1",
  },
  {
    id: "order-2_xyz456",
    price: 24.5,
    quantity: 2,
    status: "fulfilled",
    description: "Description for order 2",
  },
  {
    id: "order-3_def789",
    price: 32.0,
    quantity: 1,
    status: "in process",
    description: "Description for order 3",
  },
  {
    id: "order-1_abc123",
    price: 15.99,
    quantity: 3,
    status: "in process",
    description: "Description for order 1",
  },
  {
    id: "order-2_xyz456",
    price: 24.5,
    quantity: 2,
    status: "fulfilled",
    description: "Description for order 2",
  },
  {
    id: "order-3_def789",
    price: 32.0,
    quantity: 1,
    status: "in process",
    description: "",
  },
  {
    id: "order-4_ghi101",
    price: 10.0,
    quantity: 5,
    status: "rejected",
    description: "Description for order 4",
  },
  {
    id: "order-5_jkl202",
    price: 45.75,
    quantity: 2,
    status: "fulfilled",
    description: "Description for order 5",
  },
  {
    id: "order-6_mno303",
    price: 18.0,
    quantity: 1,
    status: "in process",
    description: "Description for order 6",
  },
  {
    id: "order-7_pqr404",
    price: 28.99,
    quantity: 4,
    status: "fulfilled",
    description: "Description for order 7",
  },
  {
    id: "order-8_stu505",
    price: 12.5,
    quantity: 2,
    status: "rejected",
    description: "Description for order 8",
  },
  {
    id: "order-9_vwx606",
    price: 36.75,
    quantity: 3,
    status: "in process",
    description: "Description for order 9",
  },
  {
    id: "order-10_yz707",
    price: 22.0,
    quantity: 1,
    status: "fulfilled",
    description: "Description for order 10",
  },
  {
    id: "order-11_ab808",
    price: 8.5,
    quantity: 2,
    status: "in process",
    description: "Description for order 11",
  },
  {
    id: "order-12_cd909",
    price: 19.99,
    quantity: 3,
    status: "fulfilled",
    description: "Description for order 12",
  },
  {
    id: "order-13_ef010",
    price: 50.0,
    quantity: 1,
    status: "in process",
    description: "Description for order 13",
  },
  {
    id: "order-14_gh111",
    price: 13.25,
    quantity: 2,
    status: "rejected",
    description: "Description for order 14",
  },
  {
    id: "order-15_ij212",
    price: 30.5,
    quantity: 4,
    status: "fulfilled",
    description: "Description for order 15",
  },
  {
    id: "order-16_kl313",
    price: 14.0,
    quantity: 1,
    status: "in process",
    description: "Description for order 16",
  },
  {
    id: "order-17_mn414",
    price: 40.0,
    quantity: 3,
    status: "fulfilled",
    description: "Description for order 17",
  },
  {
    id: "order-18_op515",
    price: 17.5,
    quantity: 2,
    status: "rejected",
    description: "Description for order 18",
  },
  {
    id: "order-19_qr616",
    price: 22.99,
    quantity: 5,
    status: "in process",
    description: "Description for order 19",
  },
  {
    id: "order-20_st717",
    price: 25.0,
    quantity: 1,
    status: "fulfilled",
    description: "Description for order 20",
  },
];
